language: perl
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
before_install:
  - cpanm -nq Devel::Cover::Report::Coveralls
  - cpanm Carton
install:
  - carton install --deployment
script:
  - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t/" carton exec -- prove -lr t
after_success:
  - cover -report coveralls
notifications:
  irc:
    channels:
      - "chat.freenode.net#oklahomer"
    on_success: always
    on_failure: always
